// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: egayoznxicswvkcuafzi

class SupabaseConfig {
  static const String supabaseUrl = 'https://egayoznxicswvkcuafzi.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnYXlvem54aWNzd3ZrY3VhZnppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1ODk3OTEsImV4cCI6MjA3ODE2NTc5MX0.K14qY0YCawZd8jtI_D8ZBPDJpVQr22nlCUDW5Ldeo3M';
}
